name: CI

on:
  push:
    branches:
      - v3
  pull_request:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yml

  test:
    name: Test & Build
    uses: ./.github/workflows/test.yml
